---
- name: Apache Hello World
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present
      changed_when: false
    - name: Create a default page
      shell: echo "<h1>Hello world from Terraform Cloud</h1>" > /var/www/html/index.html
      changed_when: false
    - name: Enable Apache
      service: name=httpd enabled=yes state=started
      changed_when: false